### ISSUE TITLE
Scripts for ADE20K

### ISSUE THREAD

**Issue by JACK-Chen-2019** [zkzhang98/CoinSeg#3]
Could you please provide the scripts for ADE20k? 
We are utilizing two 24GB memory 3090 GPUs. Despite adjusting the batch size to 8 on the ADE dataset, we are still encountering "cuda out of memory" issues.

**Comment by zkzhang98** [comment]
The `script_train.py` of ADE and VOC is the same (except for the dataset path), you may try the following command of my experiments:
```
os.system(
    'python -u script_train.py 100-10 0,1,2,3,4,5 1 --freeze_low '
    f'--conloss_proposal --conloss_prototype --KDLoss --KDLoss_prelogit --model deeplabv3_swin_transformer --batch 12 '
    ' --name swin_ade')
```
